# Generated by Django 2.2.17 on 2022-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('complexity', models.CharField(max_length=128, verbose_name='сложность')),
                ('time', models.FloatField(verbose_name='время работы')),
                ('iter_count', models.IntegerField(verbose_name='кол-во итераций')),
                ('replacements_count', models.IntegerField(verbose_name='кол-во перестановок')),
                ('code_lines_count', models.IntegerField(verbose_name='кол-во строк кода')),
            ],
            options={
                'verbose_name': 'алгоритм сортировки',
                'verbose_name_plural': 'алгоритмы сортировки',
            },
        ),
    ]
