# Generated by Django 2.2.17 on 2022-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='type',
            field=models.CharField(choices=[('Обменами', 'Обменами'), ('Выбором', 'Выбором'), ('Вставками', 'Вставками')], default='Обменами', max_length=64, verbose_name='тип'),
            preserve_default=False,
        ),
    ]
