# Generated by Django 2.2.17 on 2022-03-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_algorithm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='item_count',
            field=models.IntegerField(choices=[(500, 500), (1000, 1000), (2500, 2500), (5000, 5000)], default=500, verbose_name='кол-во элементов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='sort_percent',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (25, 25), (33, 33), (50, 50), (75, 75), (90, 90)], default=0, verbose_name='процент сортировки массива'),
            preserve_default=False,
        ),
    ]
