# Generated by Django 2.2.17 on 2022-04-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_auto_20220316_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='code',
            field=models.TextField(default='def bubble(raw_data: list[int]):', verbose_name='Код на Python'),
            preserve_default=False,
        ),
    ]
