# Generated by Django 2.2.17 on 2022-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_algorithm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='description',
            field=models.TextField(default='suka', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
