# Generated by Django 4.0.4 on 2022-05-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_algorithm_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='code',
            field=models.TextField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='code_lines_count',
            field=models.IntegerField(verbose_name='Кол-во строк кода'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='item_count',
            field=models.IntegerField(choices=[(500, 500), (1000, 1000), (2500, 2500), (5000, 5000)], verbose_name='Кол-во элементов'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='iter_count',
            field=models.IntegerField(verbose_name='Кол-во итераций'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='replacements_count',
            field=models.IntegerField(verbose_name='Кол-во перестановок'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='sort_percentage',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (25, 25), (33, 33), (50, 50), (75, 75), (90, 90)], verbose_name='Процент сортировки массива'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='time',
            field=models.FloatField(verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='type',
            field=models.CharField(choices=[('Обменами', 'Обменами'), ('Выбором', 'Выбором'), ('Вставками', 'Вставками')], max_length=64, verbose_name='Тип'),
        ),
    ]
