name: main_workflow
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: [pull_request, push]

env:
  ## Sets environment variable
  API_LOGIN: X1234X  

jobs:
  job1:
    ## The type of runner that the job will run on, 
    ## here it runs on ubuntu latest
    runs-on: self-hosted
    steps:
      - name: step 1
        ## Reference your environment variables
        run: echo "The API key is:${{env.API_LOGIN}}"   

  job2:
    runs-on: self-hosted
    steps:
      - name: step 1
        ## Another way reference your environment variables
        run: echo "The API key is:%API_LOGIN%"
  
  job3:
    runs-on: self-hosted
    steps:
      - name: Print login
        run: echo "The API login is:${{ secrets.API_LOGIN }}"
      - name: Set login
        run: set API_LOGIN=${{ secrets.API_LOGIN }}
      - name: Print env
        run: echo "%API_LOGIN%"

  # job3:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print login
  #       run: echo "The API login is: ${{ secrets.API_LOGIN }}"